name: Golang CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: 01092002/swe-storage-service

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Branch Name
        id: extract_branch
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Git Commit Data
        id: git_commit_data
        uses: rlespinasse/git-commit-data-action@v1.5.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Confirm Docker Login
        run: echo "✅ Successfully logged in to Docker Hub."

      - name: Build Docker Image
        run: |
          set -e  # Exit on any error
          echo "🚀 Starting Docker image build..."

          # Extract details for tagging
          TIMESTAMP=$(TZ=Asia/Ho_Chi_Minh date +"%Y%m%d%H%M%S")
          BRANCH_NAME=${{ steps.extract_branch.outputs.branch }}
          COMMIT_SHA=${{ steps.git_commit_data.outputs.short_sha }}
          IMAGE_TAG="$BRANCH_NAME-$COMMIT_SHA-$TIMESTAMP"

          echo "🔖 Tagging Docker image as $IMAGE_TAG..."
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          # Build the Docker image
          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .

      - name: Confirm Docker Build
        run: |
          echo "✅ Docker image built successfully with tags: ${{ env.IMAGE_TAG }} and latest."

      - name: Push Docker Image
        run: |
          set -e  # Exit on any error
          echo "📤 Pushing Docker images to Docker Hub..."

          # Push both tags
          docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}
          docker push $IMAGE_NAME:latest

          echo "✅ Docker images pushed successfully: $IMAGE_NAME:${{ env.IMAGE_TAG }} and $IMAGE_NAME:latest."