name: Golang CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: 01092002/swe-storage-service

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Git Commit Data
        uses: rlespinasse/git-commit-data-action@v1.5.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Confirm Docker Login
        run: echo "Successfully logged in to Docker Hub."

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          
          # Extract the branch name and commit hash
          TIMESTAMP=$(TZ=Asia/Ho_Chi_Minh date +"%Y%m%d%H%M%S")
          BRANCH_NAME=${{ steps.extract_branch.outputs.branch }}
          COMMIT_SHA=${{ env.GIT_COMMIT_SHORT_SHA }}
          IMAGE_NAME="01092002/swe-storage-service"
          IMAGE_TAG="$BRANCH_NAME-$COMMIT_SHA-$TIMESTAMP"
          
          echo "Tagging Docker image with $IMAGE_TAG..."
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          # Build the Docker image
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Confirm Docker Build
        run: echo "Docker image built successfully with tag ${{ env.IMAGE_TAG }}."

      - name: Push Docker Image
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}
          echo "Docker image pushed successfully to Docker Hub as $IMAGE_NAME:${{ env.IMAGE_TAG }}."